welcome: "Welcome to Rock Paper Scissors Spock Lizard!  First to win five rounds wins the match."
make_choice: "Choose one: (r)ock, (p)aper (s)cissors (sp)ock (l)izard."
invalid: "Sorry, that's not a valid choice."
draw: "The round is a draw!"
win: "You win the round!"
loss: "Computer wins the round!"
play_again?: "Would you like to play again? (y)es/(n)o"
match_won: "Congratulations! You won the match."
match_lost: "Sorry, the computer won the match."
thanks: "Thank you for playing. Good bye!"