welcome: "Welcome to our mortgage calculator!"
loan_amount: "Please enter your total loan amount."
apr: "Please enter your APR as a percentage."
loan_length: "Please enter your loan duration in months."
zero: "Sorry, not a positive number."
not_number: "Sorry, please enter numbers only."
yes_or_no: "Sorry, please only enter (y)es or (n)o."
again?: "Would you like to calculate again? (y/n)"
thanks: "Thank you for using our calculator.  Goodbye!"