welcome: "Welcome to Calculator! Enter your name."
valid_name: "Make sure to use a valid name."
first_num: "What's the first number?"
valid_num: "Hmm... that doesn't look like a valid number"
second_num: "What's the second number?"
operator_prompt: "What operation would you like to perform?\n1) add\n2) subtract\n3) multiply\n4) divide"
valid_op: "Must choose 1, 2, 3 or 4"
another: "Do you want to perform another calculation? (y/n)"
thanks: "Thank you for using our calculator"